### ISSUE TITLE
Build issue - Module not found  '../../_common/services/SettingsService'

### ISSUE THREAD

**Issue by annazurawska** [SenseiProductivity/PCF.RiskMatrix#9]
Hi,

I'm following the instruction from this URL (https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls) and I'm having an issue during a build. I'm not a programmer and looking at the error I'm not sure if there is something missing in the files available to download or i miss some file/library/reference in my environment that should be created at some point. 

This is the error that I'm getting after command msbuild /t:build /restore  :

ERROR in ./SenseiPCFRiskMatrix/index.ts
Module not found : error : Can't resolve '../../_common/services/SettingsService' in 'C:\Users\ps873fz\ania\SenseiPCFRi
skMatrix' [C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj]
   @ ./SenseiPCFRiskMatrix/index.ts 155:24-73

  ERROR in C:\Users\ps873fz\ania\SenseiPCFRiskMatrix\index.ts
  ./SenseiPCFRiskMatrix/index.ts
  [tsl] ERROR in C:\Users\ps873fz\ania\SenseiPCFRiskMatrix\index.ts(6,33)
        TS2307: Cannot find module '../../_common/services/SettingsService' or its corresponding type declarations.
  [9:45:31] [build]  Failed:
C:\Users\ps873fz\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.5.5\build\Microsoft.PowerApps.MSBuild.Pcf.targets(61
,5): error : [pcf-1033] [Error] An error occurred compiling or bundling the control. [C:\Users\ps873fz\ania\SenseiPCFRi
skMatrix.pcfproj]
C:\Users\ps873fz\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.5.5\build\Microsoft.PowerApps.MSBuild.Pcf.targets(61
,5): error MSB3073: The command "npm run build -- --noColor --buildMode development --outDir "C:\Users\ps873fz\ania\out
\controls" --buildSource MSBuild" exited with code -1. [C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj]
Done Building Project "C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj" (default targets) -- FAILED.

Done Building Project "C:\Users\ps873fz\ania\Solutions\Solutions.cdsproj" (build target(s)) -- FAILED.

Build FAILED.

"C:\Users\ps873fz\ania\Solutions\Solutions.cdsproj" (build target) (1:7) ->
"C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj" (default target) (2:6) ->
(PcfBuild target) ->
  Module not found : error : Can't resolve '../../_common/services/SettingsService' in 'C:\Users\ps873fz\ania\SenseiPCF
RiskMatrix' [C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj]
  C:\Users\ps873fz\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.5.5\build\Microsoft.PowerApps.MSBuild.Pcf.targets(
61,5): error : [pcf-1033] [Error] An error occurred compiling or bundling the control. [C:\Users\ps873fz\ania\SenseiPCF
RiskMatrix.pcfproj]
  C:\Users\ps873fz\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.5.5\build\Microsoft.PowerApps.MSBuild.Pcf.targets(
61,5): error MSB3073: The command "npm run build -- --noColor --buildMode development --outDir "C:\Users\ps873fz\ania\o
ut\controls" --buildSource MSBuild" exited with code -1. [C:\Users\ps873fz\ania\SenseiPCFRiskMatrix.pcfproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:01:36.03

C:\Users\ps873fz\ania\Solutions>

After opening index.ts file in Visual Studio i see that this line is highlited in red:
import { SettingsService } from "../../_common/services/SettingsService";

Could you please advise me what i should do to make it work?

**Comment by danafallahi** [comment]
I have the same issue her, please any update?

**Comment by m-giovanni** [comment]
I had the same issue, the solution is remove all lines with "SettingsService" from index.ts | Now it's works perfectly.

**Comment by PaulMcManus23** [comment]
I have removed the settings service reference. It is from a customisation done elsewhere.
